name: binary-release

on:
  push:
    tags:
    - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
            platforms: 'linux/amd64, darwin/amd64, darwin/arm64, windows/amd64'
            package: 'cmd'
            name: 'logshark'
            compress: 'true'
            dest: 'dist'

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - 
        name: Upload Release Asset Apple Silicon
        id: upload-release-asset-m1
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./dist/logshark-darwin-arm64.tar.gz
          asset_name: logshark-darwin-arm64.tar.gz
          asset_content_type: application/gzip

      - 
        name: Upload Release Asset Darwin
        id: upload-release-asset-mac
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/logshark-darwin-amd64.tar.gz
          asset_name: logshark-darwin-amd64.tar.gz
          asset_content_type: application/gzip

      - 
        name: Upload Release Asset Linux
        id: upload-release-asset-linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./dist/logshark-linux-amd64.tar.gz
          asset_name: logshark-linux-amd64.tar.gz
          asset_content_type: application/gzip

      - 
        name: Upload Release Asset Windows
        id: upload-release-asset-win
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/logshark-windows-amd64.tar.gz
          asset_name: logshark-windows-amd64.tar.gz
          asset_content_type: application/gzip