name: docker-release

on:
  push:
    tags:
    - 'v*'

jobs:
  logshark_doo_doo_doo_doo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19.0' 

      - name: Run build Linux amd64
        run: GOOS=linux GOARCH=amd64 go build -buildmode exe -ldflags="-w -s" -o ./dist/linux-amd64/logshark ./cmd
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ugosan/logshark

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}